### ISSUE TITLE
[alpha testing] undefined URL access

### ISSUE THREAD

**Issue by lightb0x** [swsnu/swpp2019-team20#127]
`https://payback.nevivur.net/hackerthing` shows nothing, which could be security issue.

please implement `404` page to handle this issue.

example: [apple](https://www.apple.com/asdfasdf), [github](https://github.com/asdfasdfasdfasdfasdfefe)

**Comment by taehioum** [comment]
On the other hand, https://payback.nevivur.net/profile/3333333333333333332343434 shows a non existent empty user.
