### ISSUE TITLE
[Alpha Testing] Error content 

### ISSUE THREAD

**Issue by desiderare** [swsnu/swpp2019-team20#128]
Register를 누르면 error가 뜨는데, participant가 부족할 때는 알려주나 그 이외에 이유를 알려주지 않습니다. 이유를 알려준다면 더 좋을 것 같습니다!

**Comment by lightb0x** [comment]
<img width="1440" alt="스크린샷 2019-12-05 오후 7 34 48" src="https://user-images.githubusercontent.com/17784659/70227787-8c06a380-1796-11ea-93ce-baec518c8d21.png">
