### ISSUE TITLE
[alpha testing] my page 

### ISSUE THREAD

**Issue by sungbin92** [swsnu/swpp2019-team20#130]
제가 못찾는 건지 모르겠는데 loan관련 사항 success하고 올려도 현재 상황을 확인할 수 있는 페이지를 못찾겠습니다..

**Comment by coffeetea99** [comment]
본인이 거래에 포함되어 있는지 확인해 주세요.

**Comment by nungnung** [comment]
mypage에서는 완료된 loan들이 보여집니다. 완료된 loan인지 확인해주세요.

**Comment by sungbin92** [comment]
저를 포함해서 하니까 되는데 done 표시가 떠도 마이페이지에 완료된 Loan들로 뜨지는 않는거같습니다.

**Comment by sungbin92** [comment]
아직 진행상황이 더 남은 것 같네요

**Comment by nungnung** [comment]
거래에 참여한 사람들 모두(양쪽)이 confirm버튼을 눌러 Status가 PayMeBack!에서 바뀌었는지 확인 부탁드려요.

**Comment by sungbin92** [comment]
혼자서 하다보니 제대로 테스트가 잘 안되네요 ㅠ 그런데 한 아이디로 borrower sender 둘 다 설정이 가능한 것 같습니다.
