### ISSUE TITLE
[alpha testing]

### ISSUE THREAD

**Issue by gywls00** [swsnu/swpp2019-team20#131]
다른 분들은 register가 되는데 왜인지 모르겠지만 register를 누르면 error 가 뜹니다
실수로 participant 추가했을 떄 삭제할 수 있었으면 좋을 것 같아요

**Comment by kooyunmo** [comment]
#123

**Comment by coffeetea99** [comment]
검색창에서 사람 이름을 검색하고 반드시 그 이름을 클릭하셔야 합니다.

**Comment by lightb0x** [comment]
검색 후 대상이 설정되었는지 아닌지 확인할 수 있으면 좋을 것 같습니다!
