### ISSUE TITLE
[backend&frontend] Loan creation

### ISSUE THREAD

**Issue by nevivurn** [swsnu/swpp2019-team20#24]
Create both the frontend & backend for loan creation.

**Comment by nevivurn** [comment]
While implementing this feature, we've been making the following changes to the model:

- Nullable `completed_date`
- Remove `average_rating` (not in spec)
- Add `interest_type`.

Also see #18.

**Comment by coffeetea99** [comment]
Contents below are written in #28 .

-----

modification during implementation

model.py
add 'interest_type' field
The range of interest_type is [hour, day, week, month, year]
change 'interest_rate' field into float
The range of 'alert_frequency' field is [very low, low, medium, high, very high]
'expected date' field and 'completed_date' field are now nullable

requirement
python-datetutil is added

pylint
the possible number of return statements is now <=10 (<=6 previous)

-----

구현 중 수정사항

model.py
interest_type 필드를 추가함
interest_type 필드가 가질 수 있는 값은 [hour, day, week, month, year] 중 하나
interest_rate 필드를 float으로 바꿈
alert_frequency 필드가 가질 수 있는 값은 [very low, low, medium, high, very high] 중 하나
'expected_date' 필드와 'completed_date' 필드는 이제 nullable임

requirement
python-datetutil이 추가됨

pylint
한 block에서 적을 수 있는 return statement의 개수가 최대 10개가 됨(이전까지는 최대 6개)
