### ISSUE TITLE
[backend] loan confirmation

### ISSUE THREAD

**Issue by nevivurn** [swsnu/swpp2019-team20#94]
We must allow users to confirm loan status. Also, notify affected parties (see #93).

**Comment by nevivurn** [comment]
The confirmation API logic has been implemented over at `backend-confirms`, but I have been unable to test the SMS notifications.

**Comment by nungnung** [comment]
Could you pr backend-confirms now, before completing the notification? 
Since I've implemented a frontend-confirmation, it would be easy to demo if you do so.
